//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::compact_u64::CompactU64;
use crate::types::{AccountInfoDeltaAssertion, DataValueDeltaAssertion};
use borsh::BorshDeserialize;
use borsh::BorshSerialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum AccountDeltaAssertion {
    AccountInfo {
        a_offset: CompactU64,
        assertion: AccountInfoDeltaAssertion,
    },
    Data {
        a_offset: CompactU64,
        b_offset: CompactU64,
        assertion: DataValueDeltaAssertion,
    },
}
